# syntax=docker/dockerfile:1
FROM --platform=linux/amd64 mwader/static-ffmpeg:8.0.1@sha256:9a4bf2b7915ef1c4d725a176159438146b68485cc613bf6662e2786c661cd16d AS ffmpeg
FROM --platform=linux/amd64 mcr.microsoft.com/playwright/python:v1.58.0-noble@sha256:cd8493e380df200a471821e2690b710eab8d793dde3c0946fd0a39a961022914

COPY --from=ffmpeg /ffmpeg /usr/local/bin/ffmpeg
COPY --from=ffmpeg /ffprobe /usr/local/bin/ffprobe

ENV PLAYWRIGHT_BROWSERS_PATH=/ms-playwright
WORKDIR /work
ENTRYPOINT ["python3"]
